wercker/wercker

wercker.yml

Also add `=` to solve warning.

Update locations of variables

---

docker/pipeline.go

Add aftersteps to the correct slice

---

docker/docker.go

Also fixes some issues with `--docker-local`

Fix scratch n push

---

triage.yml

@termie uses this tool to manage issues

update the triage project

---

changelog.md

you know, for releases and stuff

adds a changelog

---

docker/docker.go

if the docker local flag is on, we don't push to a remote repository.
from our docs:
```
Docker local
--docker-local
This flag can be used with either wercker dev or wercker build. When using this flag, wercker will not attempt to connect to a remote repository when pulling or pushing images, but will instead look for container images locally, or when using the internal/docker-push, it will push images to the local repository.
```

respect docker local on push

---

wercker.yml

This is a requirement for automating our brew deployment automation

Generate SHA256 hashes for binaries

---

cmd/flags.go

Make working-dir environment-configurable.

---

core/options.go
test-all.sh
tests/projects/local-deploy/latest-no-yml/wercker.yml
tests/projects/local-deploy/latest-yml/wercker.yml
tests/projects/local-deploy/specific-no-yml/wercker.yml
tests/projects/local-deploy/specific-yml/last_build/wercker.yml
tests/projects/local-deploy/specific-yml/wercker.yml

checks target first, then defaults to cwd

local deploys are now smarter about wercker.yml

---

cmd/builder.go

not sure why this was here originally, maybe @mwhooker can clarify

allow images to be pulled by local service builds

---

docker/docker.go

dont add a pipeline tag for docker images

---

cmd/main.go
test-all.sh
tests/projects/artifact-size/wercker.yml

provide messages about failed artifact storage

---

core/artifact.go

report the tar path for artifacts

---

core/s3store.go
glide.lock
glide.yaml

- bumps aws go dependency for ferengi

bumps s3 dependency

---

core/pipeline.go

Revert "Output a descriptive error message when setup environment fails"

---

wercker.yml

i think our old usage was deprecated

fix go vet

---

cmd/runner.go

Emit config before parsing pipeline

---

core/options.go
docker/build.go
docker/deploy.go

should fix slack notifications

fix run/build/deploy url vars

---

cmd/flags.go
core/config.go
core/options.go
docker/box.go
docker/service.go

exposed ports for services

---

cmd/main.go
cmd/runner.go
util/util.go
util/util_test.go

Exactly the same as https://github.com/wercker/wercker/pull/166 except based on master rather than ferengi

cleanup old builds (master)

---

docker/pipeline.go

checks for missing box

---

core/config.go

remove trailing slash from basepath (ferengi)

---

core/config.go

remove trailing slash from basepath

---

docker/pipeline.go

fix panic when trying to run an empty pipeline (ferengi)

---

docker/artifact.go
docker/box.go
docker/docker.go
docker/service.go
docker/step.go
vendor/vendor.json

* updates fsouza/go-dockerclient
* move HostConfig to CreateContainer calls (as also described in https://github.com/wercker/wercker/issues/187#issuecomment-227372248)
* switched from `CopyFromContainer` to `DownloadFromContainer`

Update to support latest docker API

---

changelog.md
cmd/main.go
util/util.go
util/util_test.go

Add additional output when storing artifacts (ferengi)

---

changelog.md
cmd/main.go
util/util.go
util/util_test.go

Add additional output when storing artifacts (master)

---

changelog.md
core/pipeline.go

Output more descriptive error message (master)

---

Documentation/command/build.adoc
Documentation/command/check-config.adoc
Documentation/command/deploy.adoc
Documentation/command/dev.adoc
Documentation/command/pull.adoc
Documentation/command/wercker.adoc
changelog.md
cmd/documentation.go

Update documenation.
Resolves wercker/wercker-cli#32

Fix doc command

---

docker/service.go

I added a fix for persistent volume binding for services. Helped me in mounting a host directory to /data/db directory for my mongo service for dev pipeline.

fix volumes bindings for services

---

test-all.sh
tests/projects/service-volume/wercker.yml

Tests for #271 
checks to see if we are able to grep a file in a mounted directory of a service

Service volume tests

---

auth/auth_helper.go
core/config.go
core/config_test.go
docker/box.go
docker/docker.go
tests/box_structs.yml
tests/projects/azure/wercker.yml
vendor/vendor.json

- adds a new `Authenticatable` for Azure
- checks for errors if `Authenticator` wasn't able to be made
- adds test

Azure support

---

docker/docker.go

- set a registry, fixes mistake from #275

fix registry regression

---

changelog.md
core/step.go
core/step_test.go

and symlink them for rapid testing

allow relative paths for file:// dev steps

---

cmd/builder.go
cmd/main.go
cmd/runner.go
docker/artifact.go
docker/box.go
docker/box_test.go
docker/build.go
docker/deploy.go
docker/docker.go
docker/options.go
docker/pipeline.go
docker/service.go
docker/session.go
docker/shellstep.go
docker/step.go
docker/store.go
docker/test.go
docker/watchstep.go

some pre-cleanining before i add some more docker bits

remove docker prefix from docker opts

---

wercker.yml

adds support for fast fail on the canary api

Adds a new parameter for canary experiments

---

changelog.md
docker/docker.go
event/literalloghandler.go
util/logging.go
util/test.go
vendor/vendor.json

Updating `Sirupsen/logrus` to `sirupsen/logrus`, which involves updating **_everything_**

Make use of sirupsen/logrus instead of Sirupsen/logrus

---

docker/box.go

Remove extra space as per [comment](https://github.com/wercker/wercker/pull/359) from @hatchan

Remove extra space introduced in fix for #357

---

changelog.md

This PR updates the changelog prior to pushing this into production.

Pr 372 to production

---

changelog.md

Production release for PR #381

Production release for PR #381, Fixes Issue #364 - Upgrade azure client to allow docker push in all regions

---

changelog.md
docker/docker_kill.go
docker/docker_network.go
docker/docker_run.go

Resolved review comments received(https://github.com/wercker/wercker/pull/405) after branch merged to master branch.

docker files integration review comments

---

changelog.md

Updated version number for release
https://app.wercker.com/wercker/wercker/runs/build/5af179641af74e00012b67b3?step=5af1796a2737e00001acd8c9

Docker files integration release

---

cmd/flags.go
cmd/main.go
cmd/runner.go
core/localfilestore.go
core/options.go
docker/artifact.go
external/configure.go
external/controller.go
external/ocir.go

This is a replacement pull request for the one that disappeared after resolving merge issues. 
This completes WRKR-260
Various editorial changes to messages
Minor cleanup fixes.

Wercker config command

---

changelog.md

Updated release version in changelog.md

Docker file integration release

---

changelog.md

Changelog update for PR#426

---

changelog.md

Wrkr 807 release - changelog update for #481

---

cmd/flags.go
core/options.go
docker/build.go
docker/deploy.go

Task : https://jira.oraclecorp.com/jira/browse/WRKR-980
Please review all these 3 prs together.
- https://github.com/wercker/trigger/pull/153
- https://github.com/wercker/kiddie-pool/pull/454
- https://github.com/wercker/wercker/pull/523

wrkr-980 : Creating WERCKER_GIT_TAG env var

---

changelog.md

Wrkr 1286 release - changelog update for #531
