cmd/main.go, tests/projects/after-steps-fail/wercker.yml
this hasn't changed in forever, we ran into this while trying to debug a
reporting error for after steps after a failed build, but this number
should be updated anyway
=> make sure the step order is incremented

test-all.sh, tests/projects/scratch-n-push/wercker.yml
adds tests for scratch push by creating a dummy container with special tags and grepping for those tags from docker images
fixes #50
=> Faiq add scratch push

cmd/flags.go, core/config.go, core/options.go, docker/box.go, test-all.sh, util/environment.go, wercker.yml
allows users to mount local volumes through a `Volumes` section in their wercker.yml file
in order to run this, users must use a `--enable-volumes` flag
we leverage this feature to test wercker inside of a wercker build container as well
=> Allow users to mount local volumes

docker/docker.go
I'm not sure about the branches, but this makes sure we have a tag set - fixes the mistakes from #85 and fixes #104
=> Faiq remove pipeline tag

core/s3store.go, glide.yaml
we need to bump our aws-sdk-go dependency in order to be able to use the [check access library] (https://github.com/wercker/docker-check-access)
relatively simple stuff has changed between the two versions, mostly regarding how you set up an uploader
=> bumps s3 dependency

cmd/flags.go, cmd/main.go, cmd/runner.go, core/box.go, core/config.go, core/options.go, core/pipeline.go, core/step.go, docker/box.go, docker/build.go, docker/docker.go, docker/pipeline.go, test-all.sh, tests/projects/checkpoint/wercker.yml, wercker.yml
base-path lets us get around many of the issues that setup-go-workspace ran
into due to having the change the name of the working dir, it can be set as
a field on a pipeline
checkpointing adds the ability to set checkpoints at steps causing the
container to get locally committed and adds a flag "--checkpoint" that will
cause the build to resume from that commit
also changed is we now remove the "source" path if it already existed in
the container, allowing builds to be chained a bit more easily
=> add checkpointing and base-path

core/pipeline.go
The problem occurred with a docker base image where mkdir /pipeline fails.
WIthout this patch the output is just that "something" failed with exit code 1. - especially annoying in the web interface when there is no easy way to enable debug.
With this patch the output is:
`Guest command failed with exit code 1: mkdir -p "/pipeline"
`
=> Output a descriptive error message when setup environment fails

glide.lock
OK although this might not seem like a critical fix, it is. Let me explain the problem: a while back i created [docker-check-access](https://github.com/wercker/docker-check-access/) in order to do authentication checking against registry providers to see if users were allowed to access local images. 
Things worked fine, but I recently noticed that pushing to docker hub was returning 400's when doing the authentication check. 
To fix this, I pinned the version of docker-reg-client in my library to the same one as we use in master
https://github.com/wercker/wercker/blob/master/glide.yaml#L49
https://github.com/wercker/docker-check-access/commit/a4b9bb5f7e8804a12a2f671441b6cccf7520fd9d
=> updates glide lock

docker/docker.go
push everytime you tag to ensure not ALL the tags for the repository get pushed to a registry
before, if you had a repository with multiple tags they would all get pushed up. this PR stops that
=> Ensure current image in repository is pushed

cmd/main.go, cmd/runner.go, util/util.go, util/util_test.go
This cleans up old build artifacts from `.wercker/builds`. The latest 2, sorted by modification date, are left intact.
This fixes #165
=> Cleanup old builds, keep latest 2

docker/pipeline.go
Fixes panic when trying to run the `check-config` command without a box definition
=> fix panic when running check-config with no box definition

cmd/main.go, util/homebrew.go, vendor/vendor.json
- try to determine if wercker was installed with homebrew
- if yes and a new version is available recommend user to use `brew upgrade wercker-cli` instead of the built in upgrade mechanism
=> recommend homebrew upgrade when installed with homebrew

changelog.md, docker/deploy.go
The bug only happened when source-dir was used. The deploy like runs
would use the dir specified by source-dir as the output, causing
subsequent runs to fail because it's likely that the dir specified by
source-dir would not exist there.
The behaviour for collecting data should now be the same for deploys
as it is for builds
resolves #151
=> Fix failing chained runs (based on runs)

cmd/main.go, test-all.sh, tests/projects/rm-pipeline/wercker.yml
Seems to work
```
--> Running step: prune
--> Running step: docker push
Pushing image for tag  differentiate_envs-0b97c3fd028c1c94779fd247e0ec6f8ea504272f-staging
Storing artifacts
Collecting files from /pipeline/output
Total artifact size: 0 B
Storing artifacts complete
```
=> handle rm -rf /pipeline

cmd/flags.go
Small change to flags to add cli visible help for the pipeline flag. #234
=> Add --pipeline to the wercker --help visible output

cmd/main.go
What i think this does- adds the run id of the current build for all of the logs that will happen in the build, as we are using 1 root logger. This field will be useful for quick analysis of runs later
=> adds a run id field for easier analysis on logs

cmd/flags.go, cmd/main.go, cmd/runner.go, core/config.go, core/options.go, tests/projects/ignore/.werckerignore, tests/projects/ignore/wercker.yml, tests/projects/ignore/werckerignore, vendor/vendor.json
This uses the library https://github.com/monochromegane/go-gitignore and supports the syntax described there.
The default location of the ignore file is .werckerignore in the project directory. It can also be specified in wercker.yml and passed to the CLI as 'ignore-file', the latter takes precedence.
If the specified file doesn't exist it is assumed to be empty and no files will be ignored.
=> Add support to ignore files when copying files to the container.

docker/box.go
This add extra check on `cmd` and `entrypoint` in order to have proper behaviour when overriding the entrypoint with an empty `cmd`. This should work:
```
push-quay:
box:
id: quay.io/wercker/cronetes
entrypoint: /bin/sh
```
Fix #218
=> Fix injection of bash into empty box's cmd with overridden entrypoint

docker/docker.go
main.go
```
package main
import (
"fmt"
"os"
)
func main() {
fmt.Println(os.Getenv("MY_ENV"))
}
```
wercker.yml
```
build:
box:
id: golang
steps:
- script:
name: build
code: |
go build -o /pipeline/source/main
deploy:
box:
id: golang
steps:
- internal/docker-scratch-push:
tag: test001
port: "5000"
repository: localhost
cmd: /main
env: "MY_ENV=my-env"
```
```
$ wercker --debug build --no-remove --direct-mount
$ wercker --debug deploy --docker-local
$ docker run localhost:test001 /main
```
expect
```
$ docker run localhost:test001 /main
my-env
```
actual
```
$ docker run localhost:test001 /main
```
=> fix missing environment for docker-scratch-push

changelog.md, cmd/flags.go, docker/box.go, docker/options.go, docker/service.go
better control limiting memory on run containers, when using services gives the services a 25% of the total memoery to split amongst themselves
=> add memory constraints for boxes and services

wercker.yml
#304 made it fast fail a string, when its actually a number. this fixes that
=> fix parameter not to be string in canary

changelog.md, core/options.go, docker/box.go, docker/docker.go, docker/shellstep.go, test-all.sh, tests/projects/bash_or_sh/wercker.yml, tests/projects/scratch-n-push/wercker.yml
- Automatically detect bash or sh for containers by default,
defaulting to bash if it is there (#301)
- Fix a small bug when doing local deploys and using a working-dir other
than .wercker (#301)
alpine containers use /bin/sh, many others use /bin/bash, our default has always been /bin/bash, but this made many containers fail until a command was set explicitly, this removes that need
re deploy bug, local deploy auto-path-lookup-magic was using a hardcoded .wrcker instead of looking at working-dir
=> automatically detect bash or sh

docker/box.go
The docker daemon does this check for us and customers are currently experiencing issues regarding pulling from GCR, so we've decided to remove this check. It should be reinvestigated in the future
=> Remove redundant pull auth check

docker/box.go
quick check for a repository before trying to get the authenticator's version of it 
fixes the panic described in #306
=> Throw error for pulling a blank repo

util/environment.go, util/environment_test.go
The GetPassthru and GetHiddenPassthru functions don't keep the order of
the Envs, that is because they range over the Environment.Map. The fix
is to range over the Environment.Order.
In addition to that we added a small refactor to put the logic of the
collection mechanism in a single function so we can avoid code
duplication.
=> Keep the order when collecting pass-through vars

tests/environment-test-load-file.env, util/environment.go, util/environment_test.go
Missed the fact that godotenv handled quotes and that wercker environment files are quoted. This fixes that.
=> fix: Handle quoted environment variable values in environment file

docker/docker.go, docker/docker_push_test.go, vendor/vendor.json
- Updates the the docker-check-access library (there was a bug fix that fixed a panic when using `.Repository()` 
- Adds a tag for branch-commit for an internal push
=> Some nice additions to the way we do the docker push and test

cmd/main.go
Fixes wercker/backlog#1575 and fixes wercker/backlog#1576.  wercker detect now detects the project as java-maven based on presence of pom.xml and java-gradle based on presence of *.gradle, or gradlew.
=> Add support for Gradle and Maven based Java projects in wercker detect.

docker/box.go
Fixes [357](https://github.com/wercker/wercker/issues/357) - Check for error after starting box. There was an extraneous check on error being null, moved the code to start container above it and captured the error
[Wercker Build run url](https://app.wercker.com/wercker/wercker/runs/build/5a9e9a5f88122900019f1ca9)
=> Fixes #357 - Check for errors in starting box container

core/session.go
See https://github.com/wercker/backlog/issues/1650 for a description of the issue which this PR fixes.
Essentially, this method previously only handled the case where the sentinel at the start of the line.
This fix handles the case (which I have seen intermittently, about 1 in 5 times when running in the CLI) when the sentinel string is appended to some previous output. When this occurs the sentinel string (and any characters that follow it - see note 1 below) are moved to a separate line.
Note 1:  Why do I copy the sentinel string *and any characters that follow it* to a separate line? The reason is that the the sentinel appears to be always followed by a space and an integer, 0 in the cases I have seen.  This is explicitly tested in the `checkLine` function, which is used by the caller …
=> Fix for #1650:  In session.go, SendChecked sometimes hangs #1650 

test-all.sh
This PR adds a comment at the top of test-all.sh to tell you how to run it. 
Rather than keep this information to myself I thought it better to share it. Obviously there's more to do with this, but that's a bigger, and separate, job.
=> Add a comment to test-all.sh

docker/watchstep.go, vendor/vendor.json
The wercker CLI build pipeline appears to be broken because of the following error in the "build dependencies" step:
```
Failed for "gopkg.in/fsnotify.v1" (failed to ping remote repo): unrecognized import path "gopkg.in/fsnotify.v1"
```
For example, I added a comment to a file (in order to trigger a build) and got this failure:
https://dev.wercker.com/wercker/wercker/runs/build/5ab5498729bb860001efad11?step=5ab549902069f00001caa073
The cause seems to be an incorrect package name in an import statement. I have fixed this and updated `vendor.json` accordingly. This immediately made the build pass:
https://dev.wercker.com/wercker/wercker/runs/build/5ab54a4929bb860001efad18
I hereby submit this PR for review
=> Fix for govendor sync failures on "gopkg.in/fsnotify.v1"

changelog.md, docker/docker.go, docker/docker_push_test.go, wercker.yml
**What this PR does / why we need it:**
Fixes [1741](https://github.com/wercker/backlog/issues/1741) 
Both internal/docker-scratch-push and internal-push steps invoke tagAndPush method which further invokes DockerClient.PushImage().In a situation where docker push call will fail due to any reason - one of which being incorrect username/password for the repository, the error is not correctly captured as the REST api call for push to docker daemon immediately returns without any error. The error message is in-fact present in progress status messages from the daemon but we were not looking at those status messages to check whether a push was indeed successful. In case of a successful push, the tag, size and SHA digest of image being pushed is present in status progress messages. In this PR - …
=> Fix #1741 Correct status reporting from docker push by parsing status messages from docker

changelog.md, cmd/main.go, cmd/runner.go, core/pipeline.go, docker/options.go, docker/watchstep.go, vendor/vendor.json, wercker.yml
**What this PR does / why we need it:**
Fixes [353](https://github.com/wercker/wercker/issues/353)
To make "go build" and "wercker build" work with golang 1.10 following changes were required to be done
- Updates to few cfssl, certificate-transparaency-go and related dependencies in vendor.json as per https://github.com/google/certificate-transparency-go/issues/153
- Updates to vendor.json to fetch golang.org/x/crypto/cryptobyte as mentioned in this post https://github.com/google/certificate-transparency-go/issues/153#issuecomment-370893611
- From golang version 1.10 - go vet also looks for package dependencies being available (as mentioned in release notes - https://golang.org/doc/go1.10#vet. Therefore an update was made to wercker.yml to invoke "govendor sync" before "govendor vet"
- In …
=> Fixes #353 - Updates to enable go build and wercker build work with golang 1.10

changelog.md, docker/box.go, docker/docker.go, docker/docker_push_test.go, vendor/vendor.json
**What this PR does / why we need it:**
Fixes [1740](https://github.com/wercker/backlog/issues/1740) 
Existing logic to infer the correct registry URL from repository and registry fields from step configuration was not consistent as mentioned in issue description. With this change
1. If no repository is specified, it is assumed that the user wants to push an image of current application for which  the build is running to wcr.io repository and therefore registry is inferred as
https://test.wcr.io/v2 and repository as test.wcr.io/<application-owner>/<application-name>
2. In case a repository is provided but no registry - registry is derived from the name of the domain (if any) from the registry - e.g. for a repository quay.io/<repo-owner>/<repo-name> - quay.io will be the registry host and …
=> Fix #1740 - Correctly infer registry and repository from step input

test-all.sh, tests/projects/docker-push/Dockerfile, tests/projects/docker-push/main.go, tests/projects/docker-push/main_test.go, tests/projects/docker-push/test.sh, tests/projects/docker-push/wercker.yml
This PR adds a new integration test for `docker-push`. This tests it in the "old" mode when it creates an image from the current container and pushes it. I added this in order to test the `env` and `labels` property, which I am documenting as part of https://github.com/wercker/backlog/issues/1676
=> New test for docker push that tests env and labels properties

tests/projects/docker-push/test.sh, tests/projects/docker-push/wercker.yml, tests/projects/multidb/wercker.yml
This PR fixes two unrelated failures in the integration tests.
The change to `tests/projects/docker-push/test.sh` is needed following the merge of PR https://github.com/wercker/wercker/pull/377 with the merge of PR https://github.com/wercker/wercker/pull/375 . Previously the registry property was not prepended to the repository property when tagging the image. Now it is.
The change to `tests/projects/multidb/wercker.yml` is needed because this test previously pulled `sutoiku/redis`, which no longer exists on Docker Hub.
=> Fix integration tests

changelog.md, cmd/flags.go, core/service.go, docker/box.go, docker/options.go, docker/service.go, test-all.sh, tests/projects/docker-n-networks/wercker.yml
Wercker cli use docker links for communication. It has been changed to use custom bridge network.
Proposal and design is described in https://confluence.oraclecorp.com/confluence/display/WRKR/Docker+Networks
=> Docker network

changelog.md, cmd/runner.go, cmd/runner_test.go, core/step.go, docker/docker.go, docker/docker_build.go, docker/docker_push_test.go, docker/publish_step.go, docker/shellstep.go, docker/store.go, docker/watchstep.go, vendor/vendor.json
Fixes [wercker/backlog#1959](https://github.com/wercker/backlog/issues/1959), [wercker/backlog#1960](https://github.com/wercker/backlog/issues/1960), [wercker/backlog#1961 ](https://github.com/wercker/backlog/issues/1961)
- Change step.InitEnv to be able to return an error in case of any initialization errors
- Added runner_test.go as unit test for InitEnv change
- Removed log.panic from few places in InitEnv and return the error instead
- Fixed docker.InferRegistryAndRepository docs, additional error handing and better error messages while evaluating registry and repository
- Enhanced error message from docker.tagAndPush for errors originating from docker daemon while doing a push
- Added test case for invalid registry and repository checking for InferrEgistryAndRepository
- vendor.json …
=> Fixes #1959, #1960, #1961 - Changes for robust error handling and reporting in docker-push

changelog.md, cmd/flags.go, cmd/main.go, core/options.go, core/service.go, core/step.go, docker/box.go, docker/docker_kill.go, docker/docker_network.go, docker/docker_run.go, docker/options.go, docker/service.go, docker/step.go, test-all.sh, tests/projects/docker-kill/test.sh, tests/projects/docker-kill/wercker.yml, tests/projects/docker-networks/test.sh, tests/projects/docker-networks/wercker.yml, tests/projects/docker-run/Dockerfile, tests/projects/docker-run/main.go, tests/projects/docker-run/wercker.yml, vendor/vendor.json
- Changes from last Review 
01) Instead of using default values for below parameter, values are specified directly. Its a good practice to specify values as change in docker version might change defaults.
"com.docker.network.bridge.enable_icc":           "true",
"com.docker.network.driver.mtu":                       "1500",
02) Environment variables are pushed to services as well. 
- Canary testing on production after customer approval.
https://app.wercker.com/Trizic/platform/runs/build/5afe68237c06ca0001ec92aa?step=5afe68b66968e60001343fd5
- previous reviews.
https://github.com/wercker/wercker/pull/405/files
https://github.com/wercker/wercker/pull/407/files
=> Dockerfile integration test

cmd/flags.go, cmd/main.go, core/options.go, external/controller.go
Introduced --base-url parameter to runner start command. This controls whether using app.wercler.com (the default when not specified) or dev.wercker.com. 
format: --base-url=https://app.wercker.com
Note: this code depends on the external runner kiddie-pool Docker image. 
Also added code to cleanup external runner containers when wercker is interrupted.
=> Allow switching between external runners on dev.wercker.com and app.wercker.com

changelog.md, cmd/documentation.go
A recent upgrade was done in wercker/wercker from github.com/wercker/codegangsta-cli to gopkg.in/urfave/cli.v1 in PR https://github.com/wercker/wercker/pull/421. The codegangsta-cli implementation had a method IsHidden() implemented in Flag interface which was no longer required in urfave/cli.v1 as a flag "Hidden" is already added- but the same change was not done to the template in documentation.go and therefore when executing wercker --help on local CLI one would get an error -
panic: template: help:18:25: executing "help" at <.IsHidden>: can't evaluate field IsHidden in type cli.Flag
goroutine 1 [running]:
github.com/wercker/wercker/cmd.setupUsageFormatter.func1(0x4db7500, 0xc4200da008, 0x4d1b311, 0x214, 0x4c54960, 0xc4202504e0) …
=> Fix WRKR-355 - change .IsHidden to .Hidden in documentation.go

changelog.md
This PR implements a user requested feature to collect the report artifacts from a step even if that step failed. Users are putting logs, screenshots, etc., into the report directory and want to be able to access them even (especially) if the step fails.
=> Update changelog for release v1.0.1262

cmd/documentation.go, cmd/main.go, cmd/main_test.go
Fixes an issue where wercker --help will fail for commands containing further subcommands (i.e. run and step). Issue existed because in https://github.com/urfave/cli/blob/8e01ec4cd3e2d84ab2fe90d8210528ffbb06d8ff/help.go#L75 - template contains a join command but the https://golang.org/pkg/text/template/ package does not contain a default function for join. Therefore we have to explicitly pass it in a https://golang.org/pkg/text/template/#FuncMap ("join": strings.Join) in documentation.go.
Also added a test for verifying all commands and subcommands for --help option.
An option "docker" was there with SkipFlagParsing as true - earlier implementation of cli implements this flag quite differently than the current version of cli (Earlier: …
=> Fix wrkr-550 - wercker --help fails for subcommands

test-all.sh, tests/projects/envvars/wercker.yml, util/environment.go, util/environment_test.go
Including backtick causes setup environment to hang.  Also escape other characters whose special meaning is preserved in bash double quotes (with the exception of $ - treat interpolation separately).
=> Escape special characters in bash exports
